### ISSUE TITLE
Clangd Crashing

### ISSUE THREAD

**Issue by Trash-af** [clangd/coc-clangd#110]
i just swithced to coc and the clangd language server is not opening.
earlier it was crashing and said
```
the server has crashed 5 times in 3 minutes.The server will not be restarted.
```
then i updated clang and llvm then it just **didn't start** . i also made my own language server but it showed slightly different behaviour. It was stuck on starting langserver forever.
then i made a docker container and just installed coc without anything else and to my surprise it worked fine.
There was some error in the logs but i didn't know to to troubleshoot it

**Logs**
the output of `:CocOpenLogs`
```
2020-11-12T19:00:40.345 INFO (pid:2415) [services] - registered service "stylelintplus"
2020-11-12T19:00:40.376 INFO (pid:2415) [plugin] - coc.nvim 0.0.79-b77dc8336e initialized with node: v14.10.1 after 621ms
2020-11-12T19:00:45.223 INFO (pid:2415) [services] - registered service "clangd"
2020-11-12T19:00:45.224 INFO (pid:2415) [services] - clangd state change: stopped => starting
2020-11-12T19:00:45.231 INFO (pid:2415) [language-client-index] - Language server "clangd" started with 2432
2020-11-12T19:00:45.236 ERROR (pid:2415) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at StreamMessageWriter.write (/home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:18391:27)
    at /home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:17539:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:17529:26)
    at Object.initialize (/home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:79702:44)
    at LanguageClient.doInitialize (/home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:81817:27)
    at LanguageClient.initialize (/home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:81813:25)
    at /home/angiras/.config/nvim/autoload/plugged/coc.nvim/build/index.js:81735:25 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-11-12T19:00:45.237 INFO (pid:2415) [services] - clangd state change: starting => stopped
2020-11-12T19:00:46.175 WARN (pid:2415) [extensions] - Extension coc-clangd activate cost more than 1s
2020-11-12T19:00:51.451 INFO (pid:2415) [completion-complete] - Results from: around,snippets,yank
2020-11-12T19:00:51.968 INFO (pid:2415) [completion-complete] - Results from: around,snippets
2020-11-12T19:00:53.046 INFO (pid:2415) [completion-complete] - Results from: around,snippets
```
**System information**
Clangd version (from the log, or `clangd --version`):11.0.0
clangd extension version (from `:CocInfo`):0.4.14
Operating system:Arch Linux

**Comment by samueltwallace** [comment]
Same here. 
```
clang -v
clang version 10.0.0
```

Using Void Linux if relevant, coc-clangd v 0.4.14.

Nothing in the log shows anything about clang, and when I do `:CocList extensions` it shows that coc-clangd is not activated, but I can't activate it!

**Comment by benawas** [comment]
Did you using clangd project setup  [https://clangd.llvm.org/installation.html#project-setup](url). I have same server has crashed 5 times error in windows, and i fixing this error by add compile_commands.json in project folder.

**Comment by fannheyward** [comment]
@Trash-af what `~/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd --version` output?

**Comment by fannheyward** [comment]
@samueltwallace you need to open a C file to active coc-clangd.

**Comment by Trash-af** [comment]
@fannheyward 
```zsh
clangd --version
clangd version 11.0.0
```
after i did a system update, the server started opening but it started crashing again and again.
![error](https://user-images.githubusercontent.com/66832356/99060062-7ebc8080-25c5-11eb-88bd-4c66b36e0218.png)
and i had yet another error in `:CocOpenLog
```
2020-11-13T15:32:13.906 ERROR (pid:3276) [language-client-client] - Notification handler 'textDocument/clangd.fileStatus' failed with message: status.onFileUpdated is not a function
```

**Comment by samueltwallace** [comment]
@fannheyward I did have a C file open. I had the same crashing issue as Trash, and after not messing with it for a few days, the extension stopped activating. I eventually did get it to activate by reinstalling coc.nvim, but suspect it will continue to act up.

The active extension may be a separate issue, but it's working now. I'm going to watch it and if it arises again, I'll open a separate issue (this seems like a slightly different problem).

**Comment by nbn22385** [comment]
I have this issue as well. 

First, I tried setting the following configuration options to lighten the processing load, with no success:
```json
  "clangd.arguments": [
    "-clang-tidy=0", "-background-index=0"
  ],
```

I found that clangd only crashes for me when using the vim-lsp-cxx-highlight plugin and opening c++ files containing very complex template code (lots of SFINAE and type_traits usage). I don't imagine this issue is specific to this plugin, but rather a clangd issue when utilizing the following setting (possibly in conjunction with the vim-lsp-cxx-highlight plugin):

`  "clangd.semanticHighlighting": true,`
