### ISSUE TITLE
clangd starts multiple times and fails to initialize

### ISSUE THREAD

**Issue by rcornall** [clangd/coc-clangd#117]
Getting this stacktrace

$ uname -r
4.15.0-123-generic
$ clangd --version
clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
$ node --version
v14.15.1

```
## versions

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v14.15.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /home/rcornall/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-17T13:22:07.002 INFO (pid:23446) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v14.15.1 after 97ms
2020-11-17T13:22:08.464 INFO (pid:23446) [services] - registered service "clangd"
2020-11-17T13:22:08.465 INFO (pid:23446) [services] - clangd state change: stopped => starting
2020-11-17T13:22:08.470 INFO (pid:23446) [language-client-index] - Language server "clangd" started with 23562
2020-11-17T13:22:08.491 INFO (pid:23446) [services] - clangd state change: starting => stopped
2020-11-17T13:22:08.491 INFO (pid:23446) [services] - clangd state change: stopped => starting
2020-11-17T13:22:08.496 INFO (pid:23446) [language-client-index] - Language server "clangd" started with 23563
2020-11-17T13:22:08.500 ERROR (pid:23446) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at StreamMessageWriter.write (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:18418:27)
    at /home/rcornall/.vim/plugged/coc.nvim/build/index.js:17566:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:17556:26)
    at Object.initialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:79591:44)
    at LanguageClient.doInitialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:81706:27)
    at LanguageClient.initialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:81702:25)
    at /home/rcornall/.vim/plugged/coc.nvim/build/index.js:81624:25 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-11-17T13:22:08.502 INFO (pid:23446) [services] - clangd state change: starting => stopped
2020-11-17T13:22:09.378 WARN (pid:23446) [extensions] - Extension coc-clangd activate cost more than 1s

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v14.15.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /home/rcornall/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-17T13:22:07.002 INFO (pid:23446) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v14.15.1 after 97ms
2020-11-17T13:22:08.464 INFO (pid:23446) [services] - registered service "clangd"
2020-11-17T13:22:08.465 INFO (pid:23446) [services] - clangd state change: stopped => starting
2020-11-17T13:22:08.470 INFO (pid:23446) [language-client-index] - Language server "clangd" started with 23562
2020-11-17T13:22:08.491 INFO (pid:23446) [services] - clangd state change: starting => stopped
2020-11-17T13:22:08.491 INFO (pid:23446) [services] - clangd state change: stopped => starting
2020-11-17T13:22:08.496 INFO (pid:23446) [language-client-index] - Language server "clangd" started with 23563
2020-11-17T13:22:08.500 ERROR (pid:23446) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at StreamMessageWriter.write (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:18418:27)
    at /home/rcornall/.vim/plugged/coc.nvim/build/index.js:17566:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:17556:26)
    at Object.initialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:79591:44)
    at LanguageClient.doInitialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:81706:27)
    at LanguageClient.initialize (/home/rcornall/.vim/plugged/coc.nvim/build/index.js:81702:25)
    at /home/rcornall/.vim/plugged/coc.nvim/build/index.js:81624:25 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-11-17T13:22:08.502 INFO (pid:23446) [services] - clangd state change: starting => stopped
2020-11-17T13:22:09.378 WARN (pid:23446) [extensions] - Extension coc-clangd activate cost more than 1s
```

I noticed it's only failing to start in some directories, with larger projects. If I start a simple test.cpp somewhere it works OK, 
Eg:

```
## versions

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v14.15.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /home/rcornall/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-17T13:21:27.649 INFO (pid:23333) [services] - registered service "clangd"
2020-11-17T13:21:27.651 INFO (pid:23333) [services] - clangd state change: stopped => starting
2020-11-17T13:21:27.657 INFO (pid:23333) [language-client-index] - Language server "clangd" started with 23345
2020-11-17T13:21:27.681 INFO (pid:23333) [services] - clangd state change: starting => running
2020-11-17T13:21:27.691 INFO (pid:23333) [services] - service clangd started
2020-11-17T13:21:27.720 INFO (pid:23333) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v14.15.1 after 219ms

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v14.15.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /home/rcornall/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-17T13:21:27.649 INFO (pid:23333) [services] - registered service "clangd"
2020-11-17T13:21:27.651 INFO (pid:23333) [services] - clangd state change: stopped => starting
2020-11-17T13:21:27.657 INFO (pid:23333) [language-client-index] - Language server "clangd" started with 23345
2020-11-17T13:21:27.681 INFO (pid:23333) [services] - clangd state change: starting => running
2020-11-17T13:21:27.691 INFO (pid:23333) [services] - service clangd started
2020-11-17T13:21:27.720 INFO (pid:23333) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v14.15.1 after 219ms
```

**Comment by rcornall** [comment]
I downgraded to coc.nvim v0.0.78, and have found root cause, I get some nicer errors:

```
## Output channel: clangd

clangd: Unknown command line argument '-–query-driver'.  Try: '/home/rcornall/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd --help'
clangd: Did you mean '--query-driver'?
clangd: Unknown command line argument '/home/rcornall/wd/****hiding..this..****sysroots/x86_64/....'.  Try: '/home/rcornall/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd --help'
```

So,

1. 1st issue was I can see It's reading my  `../.vim/coc-settings.json` from some upper parent directory which I didn't realize it would do.
2. 2nd issue is I somehow had some weird hyphen character '-–' in those settings which caused clangd to fail.

But 3rd issue is why don't these nice clangd logs show up on the later coc.nvim release though.. maybe a coc.nvim issue?
