### ISSUE TITLE
formatOnType not working anymore

### ISSUE THREAD

**Issue by snprajwal** [clangd/coc-clangd#288]
I have `cocpreferences.formatOnType` set in my coc-config.json. Whenever I go to a newline, a message pops up saying "Format on type request cancelled"

This is the content of `:CocInfo`:

```
2021-07-05T13:27:49.727 ERROR (pid:3680) [node-client] - request error on "nvim_call_function" [ 'coc#highlight#get_highlights', [ 1, 'semanticTokens' ] ] Vim(let):E117: Unknown function: nvim_buf_get_extmarks Error
    at pq.request (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at pq.call (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at fD.vimGetCurrentHighlights (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:252:8104)
    at fD.doHighlight (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:252:7519)
2021-07-05T13:27:49.727 ERROR (pid:3680) [semanticTokens-buffer] - Error on semanticTokens highlight: Error
    at pq.request (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at pq.call (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at fD.vimGetCurrentHighlights (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:252:8104)
    at fD.doHighlight (/home/prajwalsn/.config/nvim/plugged/coc.nvim/build/index.js:252:7519)
```

**System information**
Clangd version: 12.0.0
clangd extension version: 0.11.0
Operating system: Arch Linux (5.12.13-arch1-1)

**Comment by fannheyward** [comment]
What's your vim/nvim version?

**Comment by snprajwal** [comment]
> What's your vim/nvim version?

I'm using v0.5.0

**Comment by fannheyward** [comment]
Fixed on coc.nvim master https://github.com/neoclide/coc.nvim/issues/3194
