### ISSUE TITLE
clangd.install fails if ~/.vim/coc-settings.json doesn't exist yet

### ISSUE THREAD

**Issue by augustfengd** [clangd/coc-clangd#344]
Hi all !

I was trying to install the language server using `:CocCommand clangd.install` but I was returned the following message: `client coc abnormal exit with: -1`.

traces from `:messages` command:

```
[coc.nvim] clangd was not found on your PATH. :CocCommand clangd.install will install 12.0.1.
[coc.nvim] Reusing existing 12.0.1 installation in /home/aug0stus/.config/coc/extensions/coc-clangd-data
client coc abnormal exit with: -1
client coc stopped!
starting coc.nvim service
[coc.nvim] clangd was not found on your PATH. :CocCommand clangd.install will install 12.0.1.
```

Found a neat command `:CocOpenLog` to open coc.nvim's log file. A refresh after running the installation command shows the following:

```
2021-08-31T23:50:24.091 INFO (pid:11459) [attach] - receive notification: runCommand [ 'clangd.install' ]
2021-08-31T23:50:24.330 INFO (pid:11459) [extension:coc-clangd] - glibc is 2.31 min is 2.18
2021-08-31T23:50:24.342 ERROR (pid:11459) [extensions] - Error: ENOENT: no such file or directory, open '/home/aug0stus/.vim/coc-settings.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Uv.modifyConfiguration (/home/aug0stus/.vim/plugged/coc.nvim/build/index.js:167:9177)
    at Uv.$updateConfigurationOption (/home/aug0stus/.vim/plugged/coc.nvim/build/index.js:167:9513)
    at Object.update (/home/aug0stus/.vim/plugged/coc.nvim/build/index.js:167:7729)
    at UI.set clangdPath [as clangdPath] (/home/aug0stus/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:27329:17)
    at Object.<anonymous> (/home/aug0stus/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:26622:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/aug0stus/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:26550:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/aug0stus/.vim/coc-settings.json'
}
2021-08-31T23:50:24.373 INFO (pid:11459) [attach] - Request action: detach []
```

So it seems that there's missing a case handling when the file `~/.vim/coc-settings.json` doesn't exist yet.

I don't know if this would be considered a bug, but it may be a worthwhile mention. 

Thanks !

**Comment by fannheyward** [comment]
Upgrade your coc.nvim, this has been fixed already.

**Comment by augustfengd** [comment]
Just upgraded and it looks like `~/.vim/coc-settings.json` is being created now after running `:CocCommand clangd.install`. Thanks for the help!
