### ISSUE TITLE
clangd failed to start: TypeError: import_coc8.window.createTreeView is not a function

### ISSUE THREAD

**Issue by klementtan** [clangd/coc-clangd#368]
I am currently facing this error message: 
```
 Server clangd failed to start: TypeError: import_coc8.window.createTreeView is not a function
```

**Logs**
Error logs:

```
2021-10-14T23:46:32.500 INFO (pid:34648) [services] - clangd state change: starting => running
2021-10-14T23:46:32.504 INFO (pid:34648) [services] - clangd state change: running => stopped
2021-10-14T23:46:32.505 ERROR (pid:34648) [services] - Server clangd failed to start: TypeError: import_coc8.window.createTreeView is not a function
    at ASTFeature.initialize (.../.config/coc/extensions/node_modules/coc-clangd/lib/index.js:27453:39)
    at Tv.initializeFeatures (.../.config/nvim/plugged/coc.nvim/build/index.js:210:4064)
    at .../.config/nvim/plugged/coc.nvim/build/index.js:206:5038
2021-10-14T23:47:47.723 INFO (pid:34648) [attach] - receive notification: showInfo []
```

**System information**
Clangd version (from the log, or `clangd --version`):  13.0.0

Operating system: macOs

**Comment by fannheyward** [comment]
Thank you for your feedback, I've improved the function check.

**Comment by YaQia** [comment]
I am confusing. I still get stuck by the same error...
I'm running neovim in Termux. My clang version is also 13.0.0
