### ISSUE TITLE
Error on applyEdits

### ISSUE THREAD

**Issue by Dzordzu** [clangd/coc-clangd#398]
## Error

`Error on applyEdits: (…) TypeError: Cannot read properties of null (reading 'uri')`

## General info

```
vim version: NVIM v0.6.1
node version: v17.3.0
coc.nvim version: 0.0.80-f6a947a8eb
coc.nvim directory: /home/dzordzu/.vim/plugged/coc.nvim
term: tmux
platform: linux
```

<details>
<summary>Log</summary>
<br>

```
2022-01-08T23:13:56.459 INFO (pid:2394) [coc-git] - Looking for git in: git
2022-01-08T23:13:56.552 INFO (pid:2394) [plugin] - coc.nvim 0.0.80-f6a947a8eb initialized with node: v17.3.0 after 1122ms
2022-01-08T23:13:56.584 INFO (pid:2394) [services] - registered service "clangd"
2022-01-08T23:13:56.587 INFO (pid:2394) [services] - clangd state change: stopped => starting
2022-01-08T23:13:56.631 INFO (pid:2394) [language-client-index] - Language server "clangd" started with 2515
2022-01-08T23:13:56.752 INFO (pid:2394) [services] - clangd state change: starting => running
2022-01-08T23:13:56.786 INFO (pid:2394) [services] - service clangd started
2022-01-08T23:14:11.706 INFO (pid:2394) [attach] - receive notification: rename []
2022-01-08T23:14:14.868 ERROR (pid:2394) [workspace] - Error on applyEdits: {
  changes: {
    'file:///home/dzordzu/400G/school/evoll/algos/ga/include/Dzordzu/GeneticAlgorithm.hpp': [ [Object] ],
    'file:///home/dzordzu/school/evoll/algos/ga/include/Dzordzu/GeneticAlgorithm.hpp': [ [Object], [Object] ]
  }
} TypeError: Cannot read properties of null (reading 'uri')
    at IW.applyEdit (/home/dzordzu/.vim/plugged/coc.nvim/build/index.js:179:30726)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async gw.rename (/home/dzordzu/.vim/plugged/coc.nvim/build/index.js:256:8074)
    at async Rw.cocAction (/home/dzordzu/.vim/plugged/coc.nvim/build/index.js:256:55603)
    at async pF.<anonymous> (/home/dzordzu/.vim/plugged/coc.nvim/build/index.js:256:57209)
2022-01-08T23:14:14.872 WARN (pid:2394) [plugin] - Slow action "rename" cost 3164ms
2022-01-08T23:14:56.381 INFO (pid:2394) [attach] - receive notification: rename []
2022-01-08T23:14:57.459 WARN (pid:2394) [plugin] - Slow action "rename" cost 1076ms
2022-01-08T23:14:58.721 INFO (pid:2394) [attach] - receive notification: rename []
2022-01-08T23:15:00.802 WARN (pid:2394) [completion] - Document not attached, suggest disabled.

```

</details>

<details>
<summary>Images</summary>
<br>

![image](https://user-images.githubusercontent.com/17514622/148662042-70c585ef-e4ef-4398-8127-929f36c3a2af.png)
![image](https://user-images.githubusercontent.com/17514622/148662050-fdfd104a-018a-498a-8148-1f404053e6ad.png)
![image](https://user-images.githubusercontent.com/17514622/148662053-87447084-2b0e-4131-adcd-e2b73e8b89db.png)

</details>

## Compile commands

```
[
{
  "directory": "/home/dzordzu/400G/school/evoll/algos/ga/build",
  "command": "/usr/bin/c++  -I/home/dzordzu/400G/school/evoll/algos/ga/include -I/home/dzordzu/400G/school/evoll/algos/ga/src -O3 -DNDEBUG -o CMakeFiles/GeneticAlgorithm.dir/src/GeneticAlgorithm.cpp.o -c /home/dzordzu/400G/school/evoll/algos/ga/src/GeneticAlgorithm.cpp",
  "file": "/home/dzordzu/400G/school/evoll/algos/ga/src/GeneticAlgorithm.cpp"
},
{
  "directory": "/home/dzordzu/400G/school/evoll/algos/ga/build",
  "command": "/usr/bin/c++  -I/home/dzordzu/400G/school/evoll/algos/ga/include -O3 -DNDEBUG -o CMakeFiles/GeneticAlgorithm_example_continuous.dir/examples/continuous.cpp.o -c /home/dzordzu/400G/school/evoll/algos/ga/examples/continuous.cpp",
  "file": "/home/dzordzu/400G/school/evoll/algos/ga/examples/continuous.cpp"
},
{
  "directory": "/home/dzordzu/400G/school/evoll/algos/ga/build",
  "command": "/usr/bin/c++  -I/home/dzordzu/400G/school/evoll/algos/ga/include -O3 -DNDEBUG -o CMakeFiles/GeneticAlgorithm_example_discrete.dir/examples/discrete.cpp.o -c /home/dzordzu/400G/school/evoll/algos/ga/examples/discrete.cpp",
  "file": "/home/dzordzu/400G/school/evoll/algos/ga/examples/discrete.cpp"
}
]
```

## Possible issues

1. Instead of unwrapped object, changes get a stringified object type ( `Object` )
2. A new version of coc broken compatibility with the previous versions
3. An update has broken uri field

## Places to search

1. https://github.com/clangd/coc-clangd/blob/master/src/cmds.ts#L56-L59
2. https://github.com/clangd/coc-clangd/blob/master/src/cmds.ts#L31-L33
3. https://github.com/clangd/coc-clangd/blob/master/src/cmds.ts#L108

**Comment by fannheyward** [comment]
The error is not related coc-clangd, but coc.nvim. From your logs, you got this error when you do rename.

I need more logs to debug this issue. Please set `clangd.trace.server` to `verbose` in your coc-settings.json, repeat your rename to reproduce this issue, then `:CocCommand workspace.showOutput clangd` to post the logs.

**Comment by fannheyward** [comment]
Upgrade your coc.nvim and try again, this should be fixed in latest release.
