### ISSUE TITLE
Failed to check for clangd update

### ISSUE THREAD

**Issue by miquecg** [clangd/coc-clangd#403]
I've installed clangd and coc-clangd. It loads fine when opening a source file but I've encountered a problem running the command `clangd.update`.

**Logs**
```
2022-01-31T14:05:43.771 INFO (pid:9075) [extension:coc-clangd] - Failed to check for clangd update:  TypeError: Invalid comparator: Features:
    at Comparator.parse (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7648:17)
    at new Comparator (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7636:14)
    at /home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7336:252
    at Array.map (<anonymous>)
    at Range3.parseRange (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7336:238)
    at /home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7290:67
    at Array.map (<anonymous>)
    at new Range3 (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7290:46)
    at new Range3 (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7277:20)
    at outside (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7882:15)
    at Object.gtr (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:7940:44)
    at rangeGreater (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:21849:23)
    at Object.<anonymous> (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:21787:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/seth/.config/coc/extensions/node_modules/coc-clangd/lib/index.js:21541:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-31T14:06:06.989 INFO (pid:9075) [attach] - Request action: commandList [ 'clangd.u', 'CocCommand clangd.u', 19 ]
2022-01-31T14:06:08.591 INFO (pid:9075) [attach] - receive notification: runCommand [ 'clangd.update' ]
2022-01-31T14:06:08.851 INFO (pid:9075) [attach] - receive notification: highlight []
2022-01-31T14:06:08.928 ERROR (pid:9075) [extension:coc-clangd] - Can't glibc version from ldd --version output: ldd (GNU libc) 2.33
2022-01-31T14:06:08.961 INFO (pid:9075) [extension:coc-clangd] - clangd  --version output:  clangd version 13.0.0
Features: linux
Platform: x86_64-pc-linux-gnu
```

**System information**
Clangd version: 13.0.0
vim version: VIM - Vi IMproved 8.2 8024106
node version: v17.4.0
coc.nvim version: 0.0.80-c1a97aab9d
clangd extension version: 0.19.0
Operating system: Arch Linux

**Comment by miquecg** [comment]
Sorry but I didn't properly read documentation and thought that `clangd.update` would update the extension itself.

My clangd installation is managed by OS package manager so it kind of makes sense that `coc-clangd` complaints when trying to update. Maybe the error message could be more informative about it but that's another topic.
