### ISSUE TITLE
clangd suddenly stop about ten seconds after starting

### ISSUE THREAD

**Issue by wan-nyan-wan** [clangd/coc-clangd#424]
In a cpp project, I tried to use coc-clangd with compile_commands.json. But clangd that is started by coc-clangd suddenly stopped about ten seconds after starting.

I investigated coc.log, but I can't find anything that helps solve it.

**Logs**
This log is from opening the cpp file.
```
2022-03-21T23:13:58.571 DEBUG (pid:94338) [core-documents] - buffer created 1 true file:///Users/hanaiikki/oss/skia/example/test/main.cc
2022-03-21T23:13:58.576 DEBUG (pid:94338) [core-editors] - editor created winid & bufnr & tabnr:  1000 1 1
2022-03-21T23:13:58.879 DEBUG (pid:94338) [sources] - created service source snippets
2022-03-21T23:13:58.880 DEBUG (pid:94338) [sources] - created service source snippets-source
2022-03-21T23:13:58.880 INFO (pid:94338) [plugin] - coc.nvim initialized with node: v14.18.2 after 372ms
2022-03-21T23:13:58.887 INFO (pid:94338) [services] - registered service "clangd"
2022-03-21T23:13:58.888 DEBUG (pid:94338) [services] - starting service: clangd
2022-03-21T23:13:58.888 INFO (pid:94338) [services] - clangd state change: stopped => starting
2022-03-21T23:13:58.906 INFO (pid:94338) [language-client-index] - Language server "clangd" started with 94377
2022-03-21T23:13:58.984 INFO (pid:94338) [services] - clangd state change: starting => running
2022-03-21T23:13:58.985 DEBUG (pid:94338) [sources] - created service source clangd
2022-03-21T23:13:58.988 INFO (pid:94338) [services] - service clangd started
2022-03-21T23:13:59.912 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:13:59.915 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:07.874 INFO (pid:94338) [services] - clangd state change: running => stopped
2022-03-21T23:14:07.874 INFO (pid:94338) [services] - clangd state change: stopped => starting
2022-03-21T23:14:07.875 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:07.893 INFO (pid:94338) [language-client-index] - Language server "clangd" started with 94724
2022-03-21T23:14:07.896 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:07.941 INFO (pid:94338) [services] - clangd state change: starting => running
2022-03-21T23:14:07.942 DEBUG (pid:94338) [sources] - created service source clangd
2022-03-21T23:14:08.638 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:08.641 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:09.509 INFO (pid:94338) [attach] - receive notification: doHover []
2022-03-21T23:14:16.731 INFO (pid:94338) [services] - clangd state change: running => stopped
2022-03-21T23:14:16.734 INFO (pid:94338) [services] - clangd state change: stopped => starting
2022-03-21T23:14:16.735 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:16.755 INFO (pid:94338) [language-client-index] - Language server "clangd" started with 94860
2022-03-21T23:14:16.756 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:16.790 INFO (pid:94338) [services] - clangd state change: starting => running
2022-03-21T23:14:16.790 DEBUG (pid:94338) [sources] - created service source clangd
2022-03-21T23:14:17.468 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:17.470 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:19.030 INFO (pid:94338) [attach] - receive notification: doHover []
2022-03-21T23:14:20.256 INFO (pid:94338) [services] - clangd state change: running => stopped
2022-03-21T23:14:20.256 INFO (pid:94338) [services] - clangd state change: stopped => starting
2022-03-21T23:14:20.256 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:20.265 INFO (pid:94338) [language-client-index] - Language server "clangd" started with 94923
2022-03-21T23:14:20.267 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:20.300 INFO (pid:94338) [services] - clangd state change: starting => running
2022-03-21T23:14:20.300 DEBUG (pid:94338) [sources] - created service source clangd
2022-03-21T23:14:20.956 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:20.958 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:21.223 INFO (pid:94338) [attach] - receive notification: doHover []
2022-03-21T23:14:28.035 INFO (pid:94338) [services] - clangd state change: running => stopped
2022-03-21T23:14:28.037 DEBUG (pid:94338) [diagnostic-buffer] - Update UI 1 [ 'clangd' ]
2022-03-21T23:14:28.039 INFO (pid:94338) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-03-21T23:14:28.646 INFO (pid:94338) [attach] - receive notification: highlight []
2022-03-21T23:14:31.756 INFO (pid:94338) [attach] - receive notification: doHover []
2022-03-21T23:14:31.763 ERROR (pid:94338) [attach] - Notification error: doHover [] Error: hover provider not found for current buffer, your language server doesn't support it.
    at Hx.checkProvier (/Users/hanaiikki/.local/share/nvim/plugged/coc.nvim/build/index.js:278:22725)
    at wx.onHover (/Users/hanaiikki/.local/share/nvim/plugged/coc.nvim/build/index.js:265:674)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Bx.cocAction (/Users/hanaiikki/.local/share/nvim/plugged/coc.nvim/build/index.js:278:34320)
    at async Y1.<anonymous> (/Users/hanaiikki/.local/share/nvim/plugged/coc.nvim/build/index.js:278:35839)
2022-03-21T23:14:32.072 INFO (pid:94338) [attach] - receive notification: highlight []
```

**System information**
Apple clangd version 13.0.0 (clang-1300.0.29.30)
vim version: NVIM v0.6.1
node version: v14.18.2
coc.nvim version: 0.0.80-47c4dee3 2022-03-13 01:40:13 +0800
Mac OS 12.1

**Comment by fannheyward** [comment]
Looks like there's something error with your clangd, try latest clangd https://github.com/clangd/clangd/releases

**Comment by kirillbobyrev** [comment]
(ideally https://github.com/clangd/clangd/releases/tag/14.0.0 - we haven't tested it fully yet but if everything goes right we'll bump the latest release to 14.0.0 soon)
