### ISSUE TITLE
[Question] Enabling inheritance related capabilities with coc-clangd

### ISSUE THREAD

**Issue by phcerdan** [clangd/coc-clangd#515]
In `ccls` it was something like `CocLocations('ccls','$ccls/inheritance')`

But I am not sure how to achieve the same with `clangd` and how to call to it using coc-clangd.

I would appreciate any help. Thanks for your time!

**Comment by fannheyward** [comment]
`$ccls/inheritance` is `ccls`'s private protocol, I don't think `clangd` supports these.

clangd supports call hierarchy and type hierarchy defined by LSP, coc.nvim also support this. Check `:h coc-callHierarchy` and `:h coc-typeHierarchy`.

**Comment by phcerdan** [comment]
Thanks @fannheyward, do you know if in `clangd` the hierarchy protocol is enabled by default? Or do I have to turn it on somehow?
I am trying: `:call CocAction('showSubTypes')` on a class declaration.
But receiving:
`[coc-nvim] Unable to get TypeHierarchyItems at cursor position`

The log shows:
```
## versions

vim version: NVIM v0.8.0
node version: v16.16.0
coc.nvim version: 0.0.82-11257dc 2022-10-08 18:52:57 -0700
coc.nvim directory: /home/x/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-10-18T12:14:22.936 INFO (pid:164888) [plugin] - coc.nvim initialized with node: v16.16.0 after 228ms
2022-10-18T12:14:22.950 INFO (pid:164888) [attach] - receive notification: highlight []
2022-10-18T12:14:22.962 INFO (pid:164888) [services] - registered service "clangd"
2022-10-18T12:14:22.963 INFO (pid:164888) [services] - LanguageClient clangd state change: stopped => starting
2022-10-18T12:14:22.967 INFO (pid:164888) [language-client-index] - Language server "clangd" started with 164916
2022-10-18T12:14:22.984 INFO (pid:164888) [services] - LanguageClient clangd state change: starting => running
2022-10-18T12:14:22.990 INFO (pid:164888) [services] - service clangd started
2022-10-18T12:14:23.961 INFO (pid:164888) [attach] - receive notification: highlight []
2022-10-18T12:14:24.724 INFO (pid:164888) [attach] - receive notification: highlight []
2022-10-18T12:14:26.994 INFO (pid:164888) [attach] - Request action: showSubTypes []
2022-10-18T12:14:26.998 ERROR (pid:164888) [provider-manager] - Provider error on prepareTypeHierarchy: ResponseError2: method not found
    at handleResponse (/home/x/.vim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/home/x/.vim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/home/x/.vim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
2022-10-18T12:14:27.310 INFO (pid:164888) [attach] - receive notification: highlight []
2022-10-18T12:14:30.535 INFO (pid:164888) [attach] - receive notification: showInfo []

```

**Comment by fannheyward** [comment]
`type hierarchy` is available in clangd 15.
