### ISSUE TITLE
Failed when jumpDefinition with error msg "invalid AST"

### ISSUE THREAD

**Issue by Piratezoe** [clangd/coc-clangd#530]
`
## versions

vim version: NVIM v0.8.0-v0.8.0
node version: v16.18.1
coc.nvim version: 0.0.82-11257dc 2022-10-08 18:52:57 -0700
coc.nvim directory: /srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-11-30T09:03:59.085 INFO (pid:66361) [services] - registered service "languageserver.bash"
2022-11-30T09:03:59.087 INFO (pid:66361) [services] - registered service "languageserver.golang"
2022-11-30T09:03:59.158 INFO (pid:66361) [services] - registered service "yaml"
2022-11-30T09:03:59.159 INFO (pid:66361) [services] - LanguageClient YAML Support state change: stopped => starting
2022-11-30T09:03:59.378 INFO (pid:66361) [plugin] - coc.nvim initialized with node: v16.18.1 after 480ms
2022-11-30T09:03:59.446 INFO (pid:66361) [services] - registered service "clangd"
2022-11-30T09:03:59.446 INFO (pid:66361) [services] - LanguageClient clangd state change: stopped => starting
2022-11-30T09:03:59.471 INFO (pid:66361) [language-client-index] - Language server "clangd" started with 66384
2022-11-30T09:03:59.626 INFO (pid:66361) [services] - LanguageClient YAML Support state change: starting => running
2022-11-30T09:03:59.640 INFO (pid:66361) [services] - service yaml started
2022-11-30T09:03:59.643 INFO (pid:66361) [services] - LanguageClient clangd state change: starting => running
2022-11-30T09:03:59.648 INFO (pid:66361) [services] - service clangd started
2022-11-30T09:03:59.674 INFO (pid:66361) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3',
  'CocDiagnosticChange'
]
2022-11-30T09:03:59.675 ERROR (pid:66361) [node-client] - Error on notification "runCommand": Command: coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 not found Error
    at NeovimClient2.echoError (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:9833:41)
    at NeovimClient2.<anonymous> (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:78479:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-30T09:03:59.675 ERROR (pid:66361) [attach] - Error: Command: coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 not found
    at CommandManager.executeCommand (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:70274:17)
    at CommandManager.fireCommand (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:70280:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Commands.runCommand (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:73174:14)
    at async Plugin.cocAction (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:78377:15)
    at async NeovimClient2.<anonymous> (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:78477:11)
2022-11-30T09:08:40.528 INFO (pid:66361) [attach] - receive notification: jumpDefinition []
2022-11-30T09:08:40.545 ERROR (pid:66361) [provider-manager] - Provider error on provideDefinition: ResponseError2: invalid AST
    at handleResponse (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/srv/data/J/cao_y1/.config/nvim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32001,
  data: undefined
}
2022-11-30T09:08:45.011 INFO (pid:66361) [attach] - receive notification: showInfo []

`

I successfully installed coc.clangd and config it with right compile_compile.json in $XDG_CONFIG_HOME/clangd/config.yaml
Also config the following clangd related content
    1   "clangd.path": "~/.config/coc/extensions/coc-clangd-data/install/15.0.3/clangd_15.0.3/bin/clangd",
    2   "clangd.enabled": true

It seems coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 was not found.
I want to know 

1.If it will cause jumpDefinition failed?
2.What else should i config beyond CocConfig and clangd.yaml?

It will be very pleased if someone have experienced the similar error and willing to share.

**Comment by fannheyward** [comment]
> coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 was not found.

Do you use `con-explorer`? It's coc-helper's issue, not coc-clangd.

**Comment by Piratezoe** [comment]
> > coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 was not found.
> 
> Do you use `con-explorer`? It's coc-helper's issue, not coc-clangd.
@fannheyward 
Thanks for your quick reply!
Yes, I have used coc-explorer.
Ok, What about Q2?
What else should i do to successfully jumpDefinition with no error (invalid AST)

My CocConfig and config.yaml under clangd are as following:

CocConfig:
{
  "suggest.noselect": true,
  "suggest.enablePreselect": false,
  "codeLens.enable": true,
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.work", "go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true
      }
    }
  },
  "explorer.icon.enableNerdfont": true,
  "explorer.file.showHiddenFiles": true,
  "explorer.enableFloatinput": true,
  "clangd.path": "~/.config/coc/extensions/coc-clangd-data/install/15.0.3/clangd_15.0.3/bin/clangd",
  "clangd.enabled": true 
}

config.yaml:

If:
  PathMatch: ".*/tsd-blueware-bluego/.*"
CompileFlags:
  CompilationDatabase: "/srv/data/J/cao_y1/recipes-svw-sop2/dev/build/phone/bt-middleware/tsd-blueware-bluego-dev/1/workspace"
---
If:
  PathMatch: ".*/tsd-blueware-api/.*"
CompileFlags:
  CompilationDatabase: "/srv/data/J/cao_y1/recipes-svw-sop2/dev/build/phone/bt-middleware/tsd-blueware-api-dev/1/workspace"
---
If:
  PathMatch: ".*/tsd-blueware-mib3-bluego-api/.*"
CompileFlags:
  CompilationDatabase: "/srv/data/J/cao_y1/recipes-svw-sop2/dev/build/phone/bt-middleware/tsd-blueware-mib3-bluego-api-dev/1/workspace"
---
If:
  PathMatch: ".*/ext-bluego/.*"
CompileFlags:
  CompilationDatabase: "/srv/data/J/cao_y1/recipes-svw-sop2/dev/build/phone/bt-middleware/ext-bluego-dev/1/workspace"

**Comment by fannheyward** [comment]
> invalid AST

This error is came from clangd, clangd failed to jump because AST error.

coc-clangd is just a client, the server didn't returns definition locations, coc-clangd can't jump.

**Comment by Piratezoe** [comment]
> > invalid AST
> 
> This error is came from clangd, clangd failed to jump because AST error.
> 
> coc-clangd is just a client, the server didn't returns definition locations, coc-clangd can't jump.

Thank you VM, I will check where goes wrong in clangd.
BTW How can enable verbose level log with coc.clangd, 
Maybe i can enable by command, Just curious.

**Comment by Piratezoe** [comment]
> > > invalid AST
> > 
> > 
> > This error is came from clangd, clangd failed to jump because AST error.
> > coc-clangd is just a client, the server didn't returns definition locations, coc-clangd can't jump.
> 
> Thank you VM, I will check where goes wrong in clangd. BTW How can enable verbose level log with coc.clangd, Maybe i can enable by command, Just curious.

ITS OK, I found that, Over the below argument.
<html>
<body>


clangd.arguments | arguments for clangd server | []
-- | -- | --



</body>
</html>

**Comment by Piratezoe** [comment]
> > > > invalid AST
> > > 
> > > 
> > > This error is came from clangd, clangd failed to jump because AST error.
> > > coc-clangd is just a client, the server didn't returns definition locations, coc-clangd can't jump.
> > 
> > 
> > Thank you VM, I will check where goes wrong in clangd. BTW How can enable verbose level log with coc.clangd, Maybe i can enable by command, Just curious.
> 
> ITS OK, I found that, Over the below argument.
> 
> clangd.arguments	arguments for clangd server	[]

Finally, Problem Solved.
This answer did greate job.
https://github.com/clangd/clangd/issues/734
The root cause is one of my cross compiler parameter seems doesn't recognized by cland server.

**Comment by Ming-Y-ANG** [comment]
I encountered a similar problem when cross-compiling the Linux 5.4 kernel code. Replacing all cc parameters in the compile_commands.json file with arm-none-linux-gnueabihf-gcc solved the problem.
