### ISSUE TITLE
Renaming is broken

### ISSUE THREAD

**Issue by eguiraud** [clangd/coc-clangd#547]
Trying to rename a variable by invoking `<Plug>(coc-rename)` while the cursor is on a variable name produces an error and also introduces characters in the text that mess up further editing.

**Logs**

```
2023-01-31T10:26:03.319 INFO (pid:1070877) [plugin] - coc.nvim initialized with node: v14.21.2 after 54ms
2023-01-31T10:26:06.195 INFO (pid:1070877) [services] - registered service "pyright"
2023-01-31T10:26:06.236 INFO (pid:1070877) [services] - registered service "clangd"
2023-01-31T10:26:06.237 INFO (pid:1070877) [services] - clangd state change: stopped => starting
2023-01-31T10:26:06.243 INFO (pid:1070877) [language-client-index] - Language server "clangd" started with 1071034
2023-01-31T10:26:06.260 INFO (pid:1070877) [services] - clangd state change: starting => running
2023-01-31T10:26:06.267 INFO (pid:1070877) [services] - service clangd started
2023-01-31T10:26:25.308 INFO (pid:1070877) [attach] - receive notification: rename []
2023-01-31T10:26:25.316 ERROR (pid:1070877) [node-client] - request error on "nvim_call_function" [
  'coc#dialog#create_prompt_win',
  [
    'New name',
    'prefix',
    {
      rounded: true,
      maxWidth: 80,
      highlight: undefined,
      borderhighlight: undefined
    }
  ]
] Vim(call):E5248: Invalid character in group name Error
    at OH.request (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:20:43405)
    at OH.call (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:25:3815)
    at Gl.show (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:150:1712)
    at /home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:267:21343
    at /home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:138:1361
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sne.requestInput (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:267:21275)
    at async iC.rename (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:289:8734)
    at async wC.cocAction (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:293:17437)
    at async OH.<anonymous> (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:293:19027)
2023-01-31T10:26:25.318 ERROR (pid:1070877) [node-client] - Error on notification "rename": Vim(call):E5248: Invalid character in group name Error
    at OH.echoError (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:26:1869)
    at OH.<anonymous> (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:293:19064)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-01-31T10:26:25.318 ERROR (pid:1070877) [attach] - Error: request error on nvim_call_function - Vim(call):E5248: Invalid character in group name
    at Gl.show (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:150:1712)
    at /home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:267:21343
    at /home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:138:1361
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sne.requestInput (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:267:21275)
    at async iC.rename (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:289:8734)
    at async wC.cocAction (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:293:17437)
    at async OH.<anonymous> (/home/blue/.local/share/nvim/plugged/coc.nvim/build/index.js:293:19027)
2023-01-31T10:26:35.415 INFO (pid:1070877) [attach] - Request action: fillDiagnostics [ 1 ]
2023-01-31T10:26:40.746 INFO (pid:1070877) [attach] - receive notification: openList []
2023-01-31T10:27:16.852 INFO (pid:1070877) [attach] - receive notification: openLog []
```

Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): 15.0.7
clangd extension version (from `:CocInfo`): 

vim version: NVIM v0.8.2
node version: v14.21.2
coc.nvim version: 0.0.82-be6ac20f 2022-08-20 17:47:53 +0800
coc.nvim directory: /home/blue/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux

Operating system: Arch Linux

**Comment by eguiraud** [comment]
Nevermind, it was a mismatch between the coc.clangd version and the coc.nvim version. Sorry for the noise!

**Comment by fannheyward** [comment]
Upgrade your coc to latest release and try again.
