### ISSUE TITLE
[coc.vim] server clangd failed to start: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by manueldgr** [clangd/coc-clangd#595]
I am currently facing this error message and I can't find any information anywhere:
`[coc.vim] server clangd failed to start: Error: spawn UNKNOWN`

**Logs**
Error logs

```
[Error - 00:52:34.308] clangd client: couldn't create connection to server.
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:757:9)
    at C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:248:6330
    at async Nd.createConnection (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:244:15252)
    at async Nd._start (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:244:7748)
    at async Object.start (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:249:5338)
```

**System information**
Clangd version (from the log, or `clangd --version`):

```
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc
```

clangd extension version (from `:CocInfo`):

```
## versions

vim version: NVIM v0.9.1
node version: v20.3.1
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2023-06-25T00:58:01.012 INFO (pid:10484) [plugin] - coc.nvim initialized with node: v20.3.1 after 399
2023-06-25T00:58:01.031 INFO (pid:10484) [services] - LanguageClient clangd state change: stopped => starting
2023-06-25T00:58:01.038 INFO (pid:10484) [services] - LanguageClient clangd state change: starting => stopped
2023-06-25T00:58:01.040 ERROR (pid:10484) [services] - Server clangd failed to start: Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:757:9)
    at C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:248:6330
    at async Nd.createConnection (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:244:15252)
    at async Nd._start (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:244:7748)
    at async Object.start (C:\Users\manux\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:249:5338) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
2023-06-25T00:58:06.686 INFO (pid:10484) [attach] - receive notification: showInfo []
```

Operating system:
windows 

I would be very grateful if someone could help me.

**Comment by erfan4323** [comment]
I have the same issue and I can't find any solution.

**Comment by manueldgr** [comment]
> I have the same issue and I can't find any solution.

If you find any solution, please let me know. :)

**Comment by IkerGimenez** [comment]
@manueldgr I downloaded the `clangd` executable from their GitHub releases page and replaced the one downloaded by `coc-clangd` and it's working as expected now. 
When I tried to run `clangd` manually before replacing the executable, a window popped up saying "this program can't run on your computer", so I assume something is wrong with the executable being downloaded by `coc-clangd`.

**Comment by fannheyward** [comment]
This has been fixed in v0.29.1.

Delete the preview downloaded clangd in `~/.config/coc/extensions/coc-clangd-data/install`, run `:CocCommand clangd.install` again.

**Comment by abid-k** [comment]
Still facing the issue even with v0.29.1

**Comment by fannheyward** [comment]
@abid-k use node v20.

**Comment by abid-k** [comment]
It didn't help either. What worked for me is to download clangd manually from github and replace the one from coc-clangd install.
