### ISSUE TITLE
[coc.nvim] Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by SHAHNUR00** [clangd/coc-clangd#657]
### I found this issue and couldn't resolve. How can I easily resolve this issue? 

![Screenshot (8)](https://github.com/clangd/coc-clangd/assets/109983076/92840687-e079-492b-b6fc-393cb5be289f)

**Comment by fannheyward** [comment]
`:CocInfo` please.

**Comment by SHAHNUR00** [comment]
`## versions

vim version: VIM - Vi IMproved 9.1 9010090
node version: v21.5.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: C:\Users\SHAHNUR\.vim\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2024-02-18T14:24:06.206 INFO (pid:988) [plugin] - coc.nvim initialized with node: v21.5.0 after 318
2024-02-18T14:24:11.866 INFO (pid:988) [configurations] - Add folder configuration from file: c:\Users\SHAHNUR\Documents\Graph\.vim\coc-settings.json
2024-02-18T14:24:12.048 INFO (pid:988) [services] - LanguageClient clangd state change: stopped => starting
2024-02-18T14:24:12.079 INFO (pid:988) [language-client-index] - Language server "clangd" started with 7040
2024-02-18T14:24:12.152 INFO (pid:988) [services] - LanguageClient clangd state change: starting => stopped
2024-02-18T14:24:12.152 INFO (pid:988) [services] - LanguageClient clangd state change: stopped => starting
2024-02-18T14:24:12.157 ERROR (pid:988) [language-client-client] - Server clangd initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:52:4644)
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:237:6192)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15472)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:244:3541)
    at t (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15121)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266)
    at et (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:26:7064)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-02-18T14:24:12.161 INFO (pid:988) [services] - LanguageClient clangd state change: starting => stopped
2024-02-18T14:24:12.168 INFO (pid:988) [language-client-index] - Language server "clangd" started with 9408
2024-02-18T14:24:12.213 INFO (pid:988) [services] - LanguageClient clangd state change: stopped => starting
2024-02-18T14:24:12.213 ERROR (pid:988) [language-client-client] - Server clangd initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:52:4644)
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:237:6192)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15472)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:244:3541)
    at t (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15121)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266)
    at et (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:26:7064)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-02-18T14:24:12.214 INFO (pid:988) [services] - LanguageClient clangd state change: starting => stopped
2024-02-18T14:24:12.214 ERROR (pid:988) [services] - Server clangd failed to start: Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:52:4644)
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:237:6192)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15472)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:244:3541)
    at t (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15121)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266)
    at et (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:26:7064)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-02-18T14:24:12.219 INFO (pid:988) [language-client-index] - Language server "clangd" started with 8080
2024-02-18T14:24:12.260 INFO (pid:988) [services] - LanguageClient clangd state change: stopped => starting
2024-02-18T14:24:12.261 ERROR (pid:988) [language-client-client] - Server clangd initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:52:4644)
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:237:6192)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15472)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:244:3541)
    at t (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15121)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266)
    at et (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:26:7064)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-02-18T14:24:12.262 INFO (pid:988) [services] - LanguageClient clangd state change: starting => stopped
2024-02-18T14:24:12.268 INFO (pid:988) [language-client-index] - Language server "clangd" started with 9096
2024-02-18T14:24:12.307 ERROR (pid:988) [language-client-client] - Server clangd initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:52:4644)
    at Object.dispose (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:237:6192)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15472)
    at Md.handleConnectionClosed (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:244:3541)
    at t (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:240:15121)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266)
    at et (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:26:7064)
    at xP.invoke (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:14497)
    at oh.fire (C:\Users\SHAHNUR\.vim\plugged\coc.nvim\build\index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-02-18T14:24:15.926 INFO (pid:988) [attach] - receive notification: highlight []
2024-02-18T14:29:50.555 INFO (pid:988) [attach] - receive notification: showInfo []

`

**Comment by fannheyward** [comment]
Your clangd starts failed, make sure clangd is installed in your $PATH and check `clangd --version`.
