### ISSUE TITLE
Add enable config option let coc-clangd not work

### ISSUE THREAD

**Issue by Elite-zx** [clangd/coc-clangd#687]
:CocConfig

<img width="372" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/8f33bc4e-e501-4309-b374-3501181ac032">

<img width="708" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/32d6b9ab-0256-414a-9659-23d4e058528d">

**Comment by fannheyward** [comment]
Your clangd failed to run, check `:CocOpenLog`

**Comment by Elite-zx** [comment]
```
2024-07-10T16:01:50.498 INFO (pid:511) [plugin] - coc.nvim initialized with node: v16.20.2 after [33m245[39m
2024-07-10T16:01:52.719 INFO (pid:511) [services] - LanguageClient clangd state change: stopped => starting
2024-07-10T16:01:52.727 INFO (pid:511) [language-client-index] - Language server "clangd" started with 539
2024-07-10T16:01:52.735 ERROR (pid:511) [language-client] - Sending request failed.
2024-07-10T16:01:52.735 ERROR (pid:511) [language-client-client] - Server clangd initialization failed. _ResponseError: write EPIPE
    at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21422:38
[90m    at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m {
  code: [33m-32099[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.738 INFO (pid:511) [services] - LanguageClient clangd state change: starting => stopped
2024-07-10T16:01:52.738 ERROR (pid:511) [services] - Server clangd failed to start: _ResponseError: write EPIPE
    at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21422:38
[90m    at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m {
  code: [33m-32099[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.738 ERROR (pid:511) [server] - unhandledRejection  Promise {
  [36m<rejected>[39m Error: write EPIPE
  [90m    at afterWriteDispatched (node:internal/stream_base_commons:160:15)[39m
  [90m    at writeGeneric (node:internal/stream_base_commons:151:3)[39m
  [90m    at Socket._writeGeneric (node:net:905:11)[39m
  [90m    at Socket._write (node:net:917:8)[39m
  [90m    at writeOrBuffer (node:internal/streams/writable:391:12)[39m
  [90m    at _write (node:internal/streams/writable:332:10)[39m
  [90m    at Socket.Writable.write (node:internal/streams/writable:336:10)[39m
      at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21827:25
      at new Promise (<anonymous>)
      at WritableStreamWrapper.write (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21818:16) {
    errno: [33m-32[39m,
    code: [32m'EPIPE'[39m,
    syscall: [32m'write'[39m
  }
} Error: write EPIPE
[90m    at afterWriteDispatched (node:internal/stream_base_commons:160:15)[39m
[90m    at writeGeneric (node:internal/stream_base_commons:151:3)[39m
[90m    at Socket._writeGeneric (node:net:905:11)[39m
[90m    at Socket._write (node:net:917:8)[39m
[90m    at writeOrBuffer (node:internal/streams/writable:391:12)[39m
[90m    at _write (node:internal/streams/writable:332:10)[39m
[90m    at Socket.Writable.write (node:internal/streams/writable:336:10)[39m
    at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21827:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21818:16) {
  errno: [33m-32[39m,
  code: [32m'EPIPE'[39m,
  syscall: [32m'write'[39m
}
2024-07-10T16:01:52.740 INFO (pid:511) [services] - LanguageClient clangd state change: stopped => starting
2024-07-10T16:01:52.743 INFO (pid:511) [language-client-index] - Language server "clangd" started with 540
2024-07-10T16:01:52.745 INFO (pid:511) [services] - LanguageClient clangd state change: starting => stopped
2024-07-10T16:01:52.745 INFO (pid:511) [services] - LanguageClient clangd state change: stopped => starting
2024-07-10T16:01:52.745 ERROR (pid:511) [language-client-client] - Server clangd initialization failed. _ResponseError: Pending response rejected since connection got disposed
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21496:25)
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75327:31)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76259:30)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76770:15)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76246:16)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:20706:24)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34) {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.745 INFO (pid:511) [services] - LanguageClient clangd state change: starting => stopped
2024-07-10T16:01:52.745 ERROR (pid:511) [server] - unhandledRejection  Promise {
  [36m<rejected>[39m _ResponseError: Pending response rejected since connection got disposed
      at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21496:25)
      at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75327:31)
      at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76259:30)
      at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76770:15)
      at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76246:16)
      at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
      at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34)
      at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:20706:24)
      at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
      at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34) {
    code: [33m-32097[39m,
    data: [90mundefined[39m
  }
} _ResponseError: Pending response rejected since connection got disposed
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21496:25)
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75327:31)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76259:30)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76770:15)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76246:16)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:20706:24)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34) {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.748 INFO (pid:511) [language-client-index] - Language server "clangd" started with 541
2024-07-10T16:01:52.750 INFO (pid:511) [services] - LanguageClient clangd state change: stopped => starting
2024-07-10T16:01:52.750 ERROR (pid:511) [language-client-client] - Server clangd initialization failed. _ResponseError: Pending response rejected since connection got disposed
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21496:25)
    at Object.dispose (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75327:31)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76259:30)
    at LanguageClient.handleConnectionClosed (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76770:15)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:76246:16)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34)
    at closeHandler (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:20706:24)
    at CallbackList.invoke (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19653:35)
    at _Emitter.fire (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:19712:34) {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.750 INFO (pid:511) [services] - LanguageClient clangd state change: starting => stopped
2024-07-10T16:01:52.753 INFO (pid:511) [language-client-index] - Language server "clangd" started with 544
2024-07-10T16:01:52.755 ERROR (pid:511) [language-client] - Sending request failed.
2024-07-10T16:01:52.755 ERROR (pid:511) [language-client-client] - Server clangd initialization failed. _ResponseError: write EPIPE
    at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21422:38
[90m    at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m {
  code: [33m-32099[39m,
  data: [90mundefined[39m
}
2024-07-10T16:01:52.756 ERROR (pid:511) [server] - unhandledRejection  Promise {
  [36m<rejected>[39m Error: write EPIPE
  [90m    at afterWriteDispatched (node:internal/stream_base_commons:160:15)[39m
  [90m    at writeGeneric (node:internal/stream_base_commons:151:3)[39m
  [90m    at Socket._writeGeneric (node:net:905:11)[39m
  [90m    at Socket._write (node:net:917:8)[39m
  [90m    at writeOrBuffer (node:internal/streams/writable:391:12)[39m
  [90m    at _write (node:internal/streams/writable:332:10)[39m
  [90m    at Socket.Writable.write (node:internal/streams/writable:336:10)[39m
      at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21827:25
      at new Promise (<anonymous>)
      at WritableStreamWrapper.write (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21818:16) {
    errno: [33m-32[39m,
    code: [32m'EPIPE'[39m,
    syscall: [32m'write'[39m
  }
} Error: write EPIPE
[90m    at afterWriteDispatched (node:internal/stream_base_commons:160:15)[39m
[90m    at writeGeneric (node:internal/stream_base_commons:151:3)[39m
[90m    at Socket._writeGeneric (node:net:905:11)[39m
[90m    at Socket._write (node:net:917:8)[39m
[90m    at writeOrBuffer (node:internal/streams/writable:391:12)[39m
[90m    at _write (node:internal/streams/writable:332:10)[39m
[90m    at Socket.Writable.write (node:internal/streams/writable:336:10)[39m
    at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21827:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:21818:16) {
  errno: [33m-32[39m,
  code: [32m'EPIPE'[39m,
  syscall: [32m'write'[39m
}
2024-07-10T16:01:52.953 INFO (pid:511) [attach] - receive notification: highlight []
2024-07-10T16:01:55.092 INFO (pid:511) [attach] - receive notification: highlight []
2024-07-10T16:01:55.869 INFO (pid:511) [attach] - receive notification: highlight []
2024-07-10T16:02:00.896 INFO (pid:511) [attach] - receive notification: openLog []

```
